---
- name: Aprovisionar VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  # vars:
  #   ssh_public_key_path: "{{ lookup('env','HOME') }}/.ssh/dftd.pub"
  tasks:
    - import_tasks: ansible/ejercicio1/main.yml
    - import_tasks: ansible/ejercicio2/main.yml
  handlers:
    - import_tasks: handlers/main.yml  # para reiniciar NGINX
